title: Project
pages: false
files: 
  fields:
    imgsize:
      type: select
      options:
        full: Fullscreen
        large: Large
        contained: Contained
      default: large
      required: true
    textcolor:
      type: select
      options:
        black: Black
        white: White
      default: black
  sortable: true
fields:
  title:
    label: Title
    type:  text
    width: 2/3
  year:
    label: Month, Year
    type: text
    width: 1/3
  client:
    label: Client
    type: tags
  place:
    label: City, Countrycode
    type: text
    width: 1/2
  exturl:
    label: URL
    type: url
    width: 1/2
  relation:
    label: Collaborator Relations
    type: select
    options:
      with: with
      for: for
      at: at
    default: with
    width: 1/3
  collaborator:
    label: Collaborator
    type: tags
    width: 2/3
  searchfilter:
    label: Category
    type: checkboxes 
    options: field
    field:
      page: inventory
      name: searchfilter
      separator: ,
options: 
  preview: false


